LINUXINCLUDE    += -I$(EVA_ROOT)/include \
                   -I$(EVA_ROOT)/include/uapi \
				   -I$(EVA_ROOT)/include/uapi/eva

#srctree is /kernel_platform/common/
ccflags-y += -I$(EVA_ROOT)/msm/eva/ \
    -I$(INCLUDEDIR)

# add flag to compile mmrm actual implementatio instead of stub version.
# to follow up with mmrm team if techpack users need to define this for long term?
KBUILD_CPPFLAGS += -DCONFIG_MSM_MMRM

# ported from Android.mk
$(info within KBUILD file KBUILD_EXTRA_SYMBOLS = $(KBUILD_EXTRA_SYMBOLS))

ifeq ($(CONFIG_ARCH_CANOE), y)
$(info within KBUILD file CONFIG_ARCH_CANOE = $(CONFIG_ARCH_CANOE))
KBUILD_CPPFLAGS += -DCONFIG_EVA_CANOE=1
ccflags-y += -DCONFIG_EVA_CANOE=1 -DCVP_FIX_DDR_TYPE=1
endif


ifeq ($(CONFIG_EVA_LE), 1)
ccflags-y += -DCONFIG_EVA_TVM=1 -Wno-error
endif

msm-eva-objs := eva/cvp.o \
        eva/msm_cvp_ioctl.o \
        eva/msm_cvp_platform.o \
        eva/msm_cvp_common.o \
        eva/msm_cvp_core.o \
        eva/msm_cvp.o \
        eva/cvp_smem.o \
        eva/msm_cvp_debug.o \
        eva/msm_cvp_res_parse.o \
        eva/cvp_hfi.o \
        eva/hfi_response_handler.o \
        eva/hfi_packetization.o \
        eva/cvp_core_hfi.o \
        eva/msm_cvp_clocks.o\
        eva/msm_cvp_buf.o \
        eva/cvp_kaanapali_hal.o \
	eva/cvp_fw_load.o \
	eva/cvp_power.o \
    eva/eva_gem.o \

obj-m += msm-eva.o

